### PR TITLE
enemies.js 

### PR DESCRIPTION
**Pull request by fijeko**
enemies.js

### CODE REVIEW

**Comment by Trion129** [comment]
There is a typo in the code, can you do a quick fix about it?

**Comment by fijeko** [comment]
Can you please point to typo, I can't find it.

**Comment by Trion129** [comment]
See in changes tab, I commented on it

**Comment by Trion129** [comment]
or to make it easier, this.chaceOfShooting should be chanceOfShooting :-)

**Comment by fijeko** [comment]
Commit amended

**Pull request merged**
